/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	chart "tkestack.io/tke/api/chart"
)

// FakeChartGroups implements ChartGroupInterface
type FakeChartGroups struct {
	Fake *FakeChart
	ns   string
}

var chartgroupsResource = schema.GroupVersionResource{Group: "chart.tkestack.io", Version: "", Resource: "chartgroups"}

var chartgroupsKind = schema.GroupVersionKind{Group: "chart.tkestack.io", Version: "", Kind: "ChartGroup"}

// Get takes name of the chartGroup, and returns the corresponding chartGroup object, and an error if there is any.
func (c *FakeChartGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *chart.ChartGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(chartgroupsResource, c.ns, name), &chart.ChartGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroup), err
}

// List takes label and field selectors, and returns the list of ChartGroups that match those selectors.
func (c *FakeChartGroups) List(ctx context.Context, opts v1.ListOptions) (result *chart.ChartGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(chartgroupsResource, chartgroupsKind, c.ns, opts), &chart.ChartGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &chart.ChartGroupList{ListMeta: obj.(*chart.ChartGroupList).ListMeta}
	for _, item := range obj.(*chart.ChartGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested chartGroups.
func (c *FakeChartGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(chartgroupsResource, c.ns, opts))

}

// Create takes the representation of a chartGroup and creates it.  Returns the server's representation of the chartGroup, and an error, if there is any.
func (c *FakeChartGroups) Create(ctx context.Context, chartGroup *chart.ChartGroup, opts v1.CreateOptions) (result *chart.ChartGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(chartgroupsResource, c.ns, chartGroup), &chart.ChartGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroup), err
}

// Update takes the representation of a chartGroup and updates it. Returns the server's representation of the chartGroup, and an error, if there is any.
func (c *FakeChartGroups) Update(ctx context.Context, chartGroup *chart.ChartGroup, opts v1.UpdateOptions) (result *chart.ChartGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(chartgroupsResource, c.ns, chartGroup), &chart.ChartGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeChartGroups) UpdateStatus(ctx context.Context, chartGroup *chart.ChartGroup, opts v1.UpdateOptions) (*chart.ChartGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(chartgroupsResource, "status", c.ns, chartGroup), &chart.ChartGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroup), err
}

// Delete takes name of the chartGroup and deletes it. Returns an error if one occurs.
func (c *FakeChartGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(chartgroupsResource, c.ns, name), &chart.ChartGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChartGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(chartgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &chart.ChartGroupList{})
	return err
}

// Patch applies the patch and returns the patched chartGroup.
func (c *FakeChartGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *chart.ChartGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(chartgroupsResource, c.ns, name, pt, data, subresources...), &chart.ChartGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroup), err
}
