/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	chart "tkestack.io/tke/api/chart"
)

// FakeChartGroupLists implements ChartGroupListInterface
type FakeChartGroupLists struct {
	Fake *FakeChart
}

var chartgrouplistsResource = schema.GroupVersionResource{Group: "chart.tkestack.io", Version: "", Resource: "chartgrouplists"}

var chartgrouplistsKind = schema.GroupVersionKind{Group: "chart.tkestack.io", Version: "", Kind: "ChartGroupList"}

// Get takes name of the chartGroupList, and returns the corresponding chartGroupList object, and an error if there is any.
func (c *FakeChartGroupLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *chart.ChartGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(chartgrouplistsResource, name), &chart.ChartGroupList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroupList), err
}

// List takes label and field selectors, and returns the list of ChartGroupLists that match those selectors.
func (c *FakeChartGroupLists) List(ctx context.Context, opts v1.ListOptions) (result *chart.ChartGroupListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(chartgrouplistsResource, chartgrouplistsKind, opts), &chart.ChartGroupListList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroupListList), err
}

// Watch returns a watch.Interface that watches the requested chartGroupLists.
func (c *FakeChartGroupLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(chartgrouplistsResource, opts))
}

// Create takes the representation of a chartGroupList and creates it.  Returns the server's representation of the chartGroupList, and an error, if there is any.
func (c *FakeChartGroupLists) Create(ctx context.Context, chartGroupList *chart.ChartGroupList, opts v1.CreateOptions) (result *chart.ChartGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(chartgrouplistsResource, chartGroupList), &chart.ChartGroupList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroupList), err
}

// Update takes the representation of a chartGroupList and updates it. Returns the server's representation of the chartGroupList, and an error, if there is any.
func (c *FakeChartGroupLists) Update(ctx context.Context, chartGroupList *chart.ChartGroupList, opts v1.UpdateOptions) (result *chart.ChartGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(chartgrouplistsResource, chartGroupList), &chart.ChartGroupList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroupList), err
}

// Delete takes name of the chartGroupList and deletes it. Returns an error if one occurs.
func (c *FakeChartGroupLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(chartgrouplistsResource, name), &chart.ChartGroupList{})
	return err
}

// Patch applies the patch and returns the patched chartGroupList.
func (c *FakeChartGroupLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *chart.ChartGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(chartgrouplistsResource, name, pt, data, subresources...), &chart.ChartGroupList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*chart.ChartGroupList), err
}
