caCrt: |
  -----BEGIN CERTIFICATE-----
  MIIDDTCCAfWgAwIBAgIBADANBgkqhkiG9w0BAQsFADAgMRAwDgYDVQQKEwdUZW5j
  ZW50MQwwCgYDVQQDEwNUS0UwHhcNMjMwNzI0MDYxNzAxWhcNMzMwNzIxMDYxNzAx
  WjAgMRAwDgYDVQQKEwdUZW5jZW50MQwwCgYDVQQDEwNUS0UwggEiMA0GCSqGSIb3
  DQEBAQUAA4IBDwAwggEKAoIBAQC4PWv4E90RhQUIFrfqG34t9XZkJdqhjH47MV1F
  yjnuQqIqJ/TiRVoywKB2+xWMEhOsAfq+G3l5FUJl21AodcoqOuOt9Xk1Sf5L/fAS
  NXTpe3g8j3UpChVIurInD08gw29FQNEzlzS2077McvKmi2JCixW/Z0bjFT8JRqGz
  d2yd16Nzp/Z6XW0M7RWHjfLaujyd1igsDYVjwYlLoMego3DN3exrc75stsuHJJiA
  efEIgmJ/SWHfl7F6aLZv0x6AtUP1uLUPbS2WWMve7QBt/8jFLGHHz2lgDrCer1wW
  gc7kl9NQs6VA+L+jai52oFbbaAgfnQIP1asrFmG3OAkq90+tAgMBAAGjUjBQMA4G
  A1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQGYFxjtQv6
  A1q9bt/gcRtY/zEjATAOBgNVHREEBzAFggNUS0UwDQYJKoZIhvcNAQELBQADggEB
  AKqcWB5R1OvQaTf0gfKUCfLb2XOOXihBK/8iy02mRfXeVWnEFsVwpTfuSqY7BGgr
  9yA2pGDIvAvLQhacsImrDuU4Qdb6BcD91xP5VdT296mXx14IaFjL7PSo27iMB8gV
  Ru6D133tgN+RDg23Id6A+F/+452c0DhayDUO+Al3+pMCctyTvsHqr4L1J6/R2Prg
  tAI3nSV064lGF7GJyzQ+wfMxK76ZyJ+SpdR0q4vaU4cAIjks8bKW/M606MOH42en
  Db51kUyG8OjLc7BMlkw/Cz2NGNGJ/GJxHuWTDrOdWk0geH2g58rsi5Pno5mdYMI+
  o9InHfnsNNmwLRcgN+O/fFo=
  -----END CERTIFICATE-----
caKey: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAuD1r+BPdEYUFCBa36ht+LfV2ZCXaoYx+OzFdRco57kKiKif0
  4kVaMsCgdvsVjBITrAH6vht5eRVCZdtQKHXKKjrjrfV5NUn+S/3wEjV06Xt4PI91
  KQoVSLqyJw9PIMNvRUDRM5c0ttO+zHLypotiQosVv2dG4xU/CUahs3dsndejc6f2
  el1tDO0Vh43y2ro8ndYoLA2FY8GJS6DHoKNwzd3sa3O+bLbLhySYgHnxCIJif0lh
  35exemi2b9MegLVD9bi1D20tlljL3u0Abf/IxSxhx89pYA6wnq9cFoHO5JfTULOl
  QPi/o2oudqBW22gIH50CD9WrKxZhtzgJKvdPrQIDAQABAoIBADp08p8B3nDCnfgV
  DUGwe3alnWzlPdtoMl0hqpCMO5lHdyCdEOwCST41NDTMMegBjFBVSHOtT/uFLU4Y
  KfTMetqvWLJHYq/vzEncRqHgaDn0vQ+qDOh6lIpBAmm2R8sDd3inujj+TvF7edxw
  1GDXdNPcQYg7gphmk1ukF4ZT7BigWvW11nn4uaNYggr2jjZLmnzmr9PsQks/NyAF
  e4IAgM5GVPRoMPsWkuAk7GJXpLx2EQpjEHHnUPHh7sXY+Wlx/zsofueZxn5rxE/w
  vc5PI4VFBoYXEyrV2ko1Ee5/5cDFjLn9cZEhfA2d8IRRCEWsBgHgZvOYK94evzQ3
  7/At00ECgYEAzqO+f0zE7WruJyLfRQxIQV3ad1XIhpIC3kZWIj5mnn/MDMBBJjBF
  ioKGeoXgb+J/bf3SpWeJC92LzFLpfQRIa1HB8vE7YDZOpf4z152Qs/oVXiT46NHM
  AtJcloM8H9UaZNMQAO/NDHYtNqXPjyD83eJhixGFcv/MZ5M0iI5o8gUCgYEA5D/o
  6+ppJ4IPBGmM25gB10t99ZmfjeHOANblNQmlTzSMAr8nAUjVPxBjwVuvjY6Sx/uQ
  wH7B6a3dxKozFruwCF6IJz3G3ZlVPM4SMo1Ai/xaT1xyeFuGjJs1l6jeRCqCaVmw
  NGzoRNq6cUzFTIIzq3vd6e5ktkHcN+gX1rC5j4kCgYEAo5tv67irvtLIBsKMhk3o
  M6EMpSmNYEbg8H4+GlTPyTSkKYBa1NKpbLZVpVK0VcG+ZSbvjjiAgJ2D313SMkKe
  2CHebuzitxWohbLT9yZw+J7MJkMdtLDPV3iZCC6V/xoqEKQv6p3y+qfiun7j7I4Q
  x9lCo+pWf6vaejNKB8jBfMUCgYAp2U3rc180TzRRqsiYupYb00uU7EXEzdHndX8w
  6kPU8d1543JTWfc/SNIBcb4ORkXDROyVXqhPIAG5PTuAv4jW//4Ws8zydFqce2v6
  uMtM30fvpROX3bAdt5dr5xpZhTHD/x2/fvhXJ4NnopvKG1U968gUTBFLGWg3F+bH
  Bj//gQKBgQCFJZnv297VzNfKm8Id0PTPIgGHjChEo/iE1h6+AhWnXFYVMXJvmSy6
  6zdZdbOCP0ByN2dd7osxI+DbQxbpF47MkeQHoI1yNnwDh/Mz2KHcy0XQKCFy6LYr
  9pksy+7BTb0F8CSgz3VBv9frFkXXo6q8f/HQf/P7TtmF/Y68brmmKg==
  -----END RSA PRIVATE KEY-----
adminCrt: |
  -----BEGIN CERTIFICATE-----
  MIIDFTCCAf2gAwIBAgIICYszBYsMGH8wDQYJKoZIhvcNAQELBQAwIDEQMA4GA1UE
  ChMHVGVuY2VudDEMMAoGA1UEAxMDVEtFMCAXDTIzMDcyNDA2MTcwMVoYDzIxMjMw
  NjMwMDYxNzAxWjApMRcwFQYDVQQKEw5zeXN0ZW06bWFzdGVyczEOMAwGA1UEAxMF
  YWRtaW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDYqFHjYQbGwk9f
  Pv51gLEy3LQC/c19lJHKrzDmOc7fro/7xFNRhEqMFlhzEAebmMoaZXLFJX7sCgwl
  dS0Q5Ohm2r+2Dkkz/o+tEjsVv/hvHrwU9b7AWuSpKVDV5FUj9SCShkIX640TP4Qf
  t7jkVTz5SwaH/35L2mDXhwq5uN3qemqPM5ibEPOY1ZJgnGOLw56UACbcyoztcw4Y
  DMltMxbigihAqqZW5Ev6b4DYeu9FaW08hpuClevIF8ohlTSt9TCNvBRC3cwtKjHY
  I+9sjRD3GE4w3s7UigCjMfozdPSx2jbWf/o5mcNjJsruUbC0fQJmJNi5BKNc11Sa
  zybpsdKjAgMBAAGjSDBGMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEF
  BQcDAjAfBgNVHSMEGDAWgBQGYFxjtQv6A1q9bt/gcRtY/zEjATANBgkqhkiG9w0B
  AQsFAAOCAQEANCLPXL8qVZi5wEYqOW9/2+ocV7z8t3YD/qc2+pxaAMueyt590YjB
  22QqZC8gMVezOd9z7pbTSS+oiX7zGn0eliMqTDEGuIKeKM7H46wXu0woA8AMZ9QI
  BY+AMCM20jRyusnBrz/a9oV7vtQBNx6rITCjf2aTNt/KnwW7mzaRg/D6RY29sGE4
  PLRcSRdpQTbux2IVQmukCior2nTcMV7YM0eFjv6A3oFdxEFhk/TI4h8lW1Qs4Rbx
  eG1KCsXj8Pc+NQTy2P3Q8VQ2jAHtAnJJW0LXhQl5SrKUblnWV+yi6XreMC+0p/wI
  opnsjXwd4ndzSNRH95zZk18W7/E6ym4aZA==
  -----END CERTIFICATE-----
adminKey: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEA2KhR42EGxsJPXz7+dYCxMty0Av3NfZSRyq8w5jnO366P+8RT
  UYRKjBZYcxAHm5jKGmVyxSV+7AoMJXUtEOToZtq/tg5JM/6PrRI7Fb/4bx68FPW+
  wFrkqSlQ1eRVI/UgkoZCF+uNEz+EH7e45FU8+UsGh/9+S9pg14cKubjd6npqjzOY
  mxDzmNWSYJxji8OelAAm3MqM7XMOGAzJbTMW4oIoQKqmVuRL+m+A2HrvRWltPIab
  gpXryBfKIZU0rfUwjbwUQt3MLSox2CPvbI0Q9xhOMN7O1IoAozH6M3T0sdo21n/6
  OZnDYybK7lGwtH0CZiTYuQSjXNdUms8m6bHSowIDAQABAoIBAGfk11flGD3JwgwX
  hihMrSyJv1zL3nWBACSkvBs6z2ReLjd6HsYxXRouQP30SuGndAsSaOX3JBUGgGqZ
  9SFr07I25cXktd/UC4vf+Stl4jlPELwwV+ef7pTb9iKLmvRiQNtivGECGKWJSM94
  55W+9j1JZ/lhYGv5bYUNAeyrpOciKQXwmAfPV4Tt9e92jd4CCi7Dgfp1TkEQ0idE
  jgn5lbh0st/Tq4cter88kcJuvXyD/H+W8qW+uwvyeIRR90jyvrcJmOo7FE6PY87j
  M/Aj7hQ3IWaesfzeoGCSUpxL88hiI41ZzPd589ax0EDvmzi5JujYD2VUijXEghoD
  s3hORlkCgYEA6pxnzWiJSmXKn5rrPijq49NhqeLITITQkYvYePEhrMHVt1A3txqO
  NMQFkutKLibGfc6WrNEzHJwmfxkKo4iIppsZFnfY8pzfFSgprhAOYjEezpQ2IFRt
  FPzEG7GY3VGR3OI8b4lYS/TjQIkZbcvI9rtDxKeKkqFBvD2i7hVbHr8CgYEA7Gjl
  3FlqTPH+gKdFdpRZidikzadLHEuLlBzo6e6cLHR5jSC3hyYr3Pa8KXLFNp8kSIYx
  JW+D9Ntmc4UewnyC2mXqFKjtthM3Vsw4G7drh64fLzKyXsnge/5AjWCpJ5NTQlwY
  pJ9nELTE46CQQoPrbqoIRCRX2SzrhuUczET9aR0CgYBIdKVaOr6ry2QYhq/AMsLY
  OaAf53oUp7ACQz5Hm7DaucJXKt8KHZltklxmU2RFfJQwpmzCUpmGbHM3LXSrrK8H
  RT8qQTkvNGNxFUZKC4tlp+XrxrowoeJOaQHny6F6OIbjwLsJd1Fdo/PLKow/7H/U
  M2FqipOxVTwH9sEq5k2N4QKBgQCAm0AQcwQE/9B3pIeBToq3Fofw6IVPyzkPRfre
  59NFy8ckIxw0BWvvNLp/wdPPNxvB6F5sAxJB7ej6Bv0IyDtXHAIPYyaN2j5MlaQg
  T9PLZ8nHH0kxj5jzWwk6386lnNu6SeeOBrlGuVAylHJl/OXiudTtXOf9WRZ3t8PG
  y/EfcQKBgQCy3AP/PYY0hV0VH6b7az5lYThvZHrc+zqUtf64ySUDlYOWJxKhuB67
  tvZzk5TIY1Qp6g+j0p+JUq9WnL9P3NWZX5YmdRlqieCuo3K00npEtI65RDqEFXSS
  E8rJdBfVBrQhhFwssMUv7JDMtmHMoa42Um0kP97DEuZw3f4Y5pJHMg==
  -----END RSA PRIVATE KEY-----
serverCrt: |
  -----BEGIN CERTIFICATE-----
  MIIFpDCCBIygAwIBAgIISRW8SsGsysswDQYJKoZIhvcNAQELBQAwIDEQMA4GA1UE
  ChMHVGVuY2VudDEMMAoGA1UEAxMDVEtFMCAXDTIzMDcyNDA2MTcwMVoYDzIxMjMw
  NjMwMDYxNzAxWjAnMRAwDgYDVQQKEwdUZW5jZW50MRMwEQYDVQQDEwpUS0UtU0VS
  VkVSMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2uxAScZFGYCLFRDa
  EvgsHsyDs4Ug2Yu6bDUqzxDcTao/Vb5TlGLTplXiX8aim8sCOMRoM2MYCPP2jwNe
  yJgdKbUEJlfslt201NQ3QuPeBO6DTXZjc96I20wcQbZSKIJG7r96w6ZMLXyGmSUf
  S3KuZdNddM6p3IwRRbyOIB6ee/uJ+2d+kHWUlhEPiFzbcn7CLmgOuDxi9yYLPp0t
  gZiTaDw4Lc51DIbZrgYtKmCs8MaqWRk4DUjElA1fVITNvQCbTW8I4Mglv8hKo00V
  4lV0p7MPczPvHjjpFr1X9BhEsKc28IlPBp8Y0my3cF8QvJuPgUav6eScMaDZPTiF
  CVFMEwIDAQABo4IC1zCCAtMwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsG
  AQUFBwMCBggrBgEFBQcDATAfBgNVHSMEGDAWgBQGYFxjtQv6A1q9bt/gcRtY/zEj
  ATCCAn8GA1UdEQSCAnYwggJyggt0a2UuZ2F0ZXdheYIJbG9jYWxob3N0ghB0a2Ut
  cGxhdGZvcm0tYXBpghh0a2UtcGxhdGZvcm0tYXBpLnRrZS5zdmOCDHBsYXRmb3Jt
  LWFwaYIQdGtlLWJ1c2luZXNzLWFwaYIYdGtlLWJ1c2luZXNzLWFwaS50a2Uuc3Zj
  ggxidXNpbmVzcy1hcGmCDnRrZS1ub3RpZnktYXBpghZ0a2Utbm90aWZ5LWFwaS50
  a2Uuc3Zjggpub3RpZnktYXBpggx0a2UtYXV0aC1hcGmCFHRrZS1hdXRoLWFwaS50
  a2Uuc3ZjgghhdXRoLWFwaYILdGtlLWdhdGV3YXmCE3RrZS1nYXRld2F5LnRrZS5z
  dmOCB2dhdGV3YXmCD3RrZS1tb25pdG9yLWFwaYIXdGtlLW1vbml0b3ItYXBpLnRr
  ZS5zdmOCC21vbml0b3ItYXBpghB0a2UtcmVnaXN0cnktYXBpghh0a2UtcmVnaXN0
  cnktYXBpLnRrZS5zdmOCDHJlZ2lzdHJ5LWFwaYIQdGtlLWxvZ2FnZW50LWFwaYIY
  dGtlLWxvZ2FnZW50LWFwaS50a2Uuc3Zjggxsb2dhZ2VudC1hcGmCDXRrZS1hdWRp
  dC1hcGmCFXRrZS1hdWRpdC1hcGkudGtlLnN2Y4IJYXVkaXQtYXBpghN0a2UtYXBw
  bGljYXRpb24tYXBpght0a2UtYXBwbGljYXRpb24tYXBpLnRrZS5zdmOCD2FwcGxp
  Y2F0aW9uLWFwaYIMdGtlLW1lc2gtYXBpghR0a2UtbWVzaC1hcGkudGtlLnN2Y4II
  bWVzaC1hcGmHBH8AAAGHBKwRAAIwDQYJKoZIhvcNAQELBQADggEBAKnd83R0rqZ5
  b/sJarKlYXqXj9ejU/3RQCyEJHWFf2jnhGvGS0HutY6SJSCBgm3Ks9B6RV+T1Si4
  5FBpWVe7H+i6nII1mptU6YVGjlnIoT1ZiWXWwF3gBt/2gC/WHu3Ywc7Qc4mB2H+U
  kzWrTeNNNmWLdGZazFq9MrEbj9CMFxKHC27Ebd9Nldqk1awMjcV37EgSVAdSTE24
  nblVdGZupv8Z7fh2CBtXd6wpyyAfswIfHFb1XLInR3ZwnD6bQT8nvDtOhUkwNhPg
  IIN6ltwEhY1RSg+hec+vWmt11oqFx3g5wusguGnJgtQ9d721sp/tlNODFZPpHsGC
  AzE0Mayg5zI=
  -----END CERTIFICATE-----
serverKey: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA2uxAScZFGYCLFRDaEvgsHsyDs4Ug2Yu6bDUqzxDcTao/Vb5T
  lGLTplXiX8aim8sCOMRoM2MYCPP2jwNeyJgdKbUEJlfslt201NQ3QuPeBO6DTXZj
  c96I20wcQbZSKIJG7r96w6ZMLXyGmSUfS3KuZdNddM6p3IwRRbyOIB6ee/uJ+2d+
  kHWUlhEPiFzbcn7CLmgOuDxi9yYLPp0tgZiTaDw4Lc51DIbZrgYtKmCs8MaqWRk4
  DUjElA1fVITNvQCbTW8I4Mglv8hKo00V4lV0p7MPczPvHjjpFr1X9BhEsKc28IlP
  Bp8Y0my3cF8QvJuPgUav6eScMaDZPTiFCVFMEwIDAQABAoIBACK9mvYaIJ0LaQbO
  xcx81YONsNisJ6peIhdJ2KFDa7JnceWJbnn9tNiQiHvqaaOPc6rOgDqnXwkMrfPD
  9Saf/QDBWQc8rK7EQA4GHz7eKj1eHDgOsXmRtuYWDeXfqOoEwnzgpfqmSTBusm1b
  FrxCVqqSACKpKQt2rscCRQuT0FKcLQYwqzT7kTMdSEZexdupskcoENLhZkD+XdHy
  NmxQ2qBlg6X4YjIAZTziVzvEUqotUqiMK/PMGqbvEemiOJezuRRl/XiQxItcO5PH
  q+MPXIUNsOEu0QnAGo8fCdfzyWrDyJ1MDUpRMd50yvndPeZMqrsJLmOIcmlS8cPk
  PR3q+QECgYEA7hAm15upcD8SY4XBC4ZGySq1eBs+doTc7HB1Eo+YnG+thjc8TsR6
  eeJJBPHoSYdkMwZVLOQAThBBIgtpG/3rRXCh92nLiGLXMcIL7cl9O7MHA9lc2v2h
  QpDJPkkUCDeDZBzeAWfZpdYuvLWFSmEFY8g/Z5zGQMJ46pw35eXPFH8CgYEA62rq
  XY/OWlRGdyUX93G+Uy8o8IjZ29iSZ6i9j49b9C7nmtZfiUZov/YWdXYFB66zrSK+
  0BXJSe9464uRAXPzDTHlC/yLQhYHxP2IDqBx1TQ5SkAM+xqoFgA0E5aYSeZN4cQx
  vOwAnrX5N88g3rBls83OViqvikIgLRUKDJMpbm0CgYB5CO02oYW789U9lDtZyKMk
  k/o/Xlqbl2FbNLHRBgDpSD5JBrw6r9o1Lb9CLFuVRqjC6G1VrXYaOlljHboK6UY8
  v88ZI0i/xsDyI149PzvUpmjipBh5nonmdgZbDHyK0O6Ub7jPriUSE5sfhoqGDl3X
  JXBXFXYWZsljPpmM4RIvsQKBgDzCzJi3bCguRj2sKkJobhokOunSOICgpjDxAXQT
  KUWd8ZMqL2BL9u9MwcExY9z2v1M5e4xTgy99CnWpARUh6yKFtTthxEObUggK89nq
  mVbQ8tRyMaeB2s5K4SYJIWc5dPKHY9sCAqr0Bs3bvP0dBDLjNJVS0RnbNVjNbFmQ
  hgoFAoGBALOOpZxBihP4xaH9p/7BbqCYZsJTst08ZbDQgUWevaVKuK3j0tSAAEnL
  6u8Hl2/8TdmaHLa49ahRNkeW7kXqQ3KFqply+LQX/udVt2Cd5U2aOdnQhcA9X9MH
  +TbZtJJO7Q/k+luMGO3PR03YhpWmYjnhk3YrwYVZ26kq2AnGx2++
  -----END RSA PRIVATE KEY-----
webhookCrt: |
  -----BEGIN CERTIFICATE-----
  MIIDEDCCAfigAwIBAgIIJ4e4IWS4IjMwDQYJKoZIhvcNAQELBQAwIDEQMA4GA1UE
  ChMHVGVuY2VudDEMMAoGA1UEAxMDVEtFMCAXDTIzMDcyNDA2MTcwMVoYDzIxMjMw
  NjMwMDYxNzAyWjAkMRAwDgYDVQQKEwdUZW5jZW50MRAwDgYDVQQDEwd3ZWJob29r
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3ligLFKwcxqhjKRimLBG
  iiddkfGvPc/bjG/SeC2+lYB3EBjYQ4YLZnf1r1WuMT2VbeRvMIdb3nLBUYQw49li
  UOm4D1YFlfJHi4auzNLEq4M80H7tcl8lZKCXeFmjR4wuJ03LQUqMGn7y+4nYSvUp
  mIOD5+0ofhIKAk844sQiPLJeV8+h5t1UiuAnQ3YzVzwp6X8wf5zLUSJkXvhXMa6O
  UiNt7NgFzzOpYSdnNjuFCEZRF6J/IhWJ/K+t/2kLlk9/imV38K6TKVk/3X8AgeMw
  wpUfA4mF767WuNWYdpU6U5WqtHEOzliOw9XYQcQhepqDLPxecSpNsBLyydZw5xrx
  WwIDAQABo0gwRjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwIw
  HwYDVR0jBBgwFoAUBmBcY7UL+gNavW7f4HEbWP8xIwEwDQYJKoZIhvcNAQELBQAD
  ggEBAB6jXsNl3Kbk4c02K8rRRlTGfNrZXQGsvD8B+Wdw+lByrH+B+aAW17xqZ+uz
  WhYlpXeFmE+3MF4Yt0EXKUDT0TUwX6Nhbj0djWnIsX2vLVLwN1ayLTEjJilf4uCu
  Z9Y0F97wQC9T4xCHZQdPpSYISKSjV3/txyAnXAhoSg4hWVnY9vSdk+TvNhWDMb4C
  V3GmOSBWALhzsZGszMFabYpUqGdJ2Sp8lExislFr7l4TLgQgKW8V5yzWZPPqwyLB
  0X6g9wdjw6cur/pZ4aCO5+YN9lSy7uvXhds7nxjyfYUt1xraj4DirdaeoW5mXJzr
  TJOb+93o3VEIngbWabH1cMttNaY=
  -----END CERTIFICATE-----
webhookKey: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA3ligLFKwcxqhjKRimLBGiiddkfGvPc/bjG/SeC2+lYB3EBjY
  Q4YLZnf1r1WuMT2VbeRvMIdb3nLBUYQw49liUOm4D1YFlfJHi4auzNLEq4M80H7t
  cl8lZKCXeFmjR4wuJ03LQUqMGn7y+4nYSvUpmIOD5+0ofhIKAk844sQiPLJeV8+h
  5t1UiuAnQ3YzVzwp6X8wf5zLUSJkXvhXMa6OUiNt7NgFzzOpYSdnNjuFCEZRF6J/
  IhWJ/K+t/2kLlk9/imV38K6TKVk/3X8AgeMwwpUfA4mF767WuNWYdpU6U5WqtHEO
  zliOw9XYQcQhepqDLPxecSpNsBLyydZw5xrxWwIDAQABAoIBAQCqP4gdiA8tg3Wx
  X+lS6p6IiE3gQwOgu7hrFvA8LyKgDKad/7gQM+IkyrOnVl6zu2jgpSnyKaLReGLH
  zQU2YawjMmJJ898BCmt3zV+o27XVcf6t0pJzoaDbJQ/2CgS48wAf/jQkwTT30L6y
  lcC03HXGHuVwP6pipeNeE1UGZZGlkKvyTQBrlqtN5Rc0/8TLvL87WFqjaSJ1N3nm
  ZQlq34GwgEad8GmVwgzu/WESlLgHd/h3MFg0HltypA/bSKFeyfHW0jH00Ks3EuhF
  iXNEIj2D9k0p35Jis7TsMNYwaIcAsTALeGEt2Zv+bTt4Sg3KCo4NiSapZg9R8zkU
  OtdXOuhJAoGBAP9TIyBAF3sugbETnSnJ9P8ju1xIy7XKVNlgORpReUBsKF726qna
  4WtX0dzp2bKRCIriR/rTQlX6mMaoZ137M8+Q0DIs9pWI20PgZHHj3atqvalUHepR
  VRjynmgFCjbI0LzfuCApW8+GlWD8gBKre6yb2CikFMWBwG0X37+Q4QU9AoGBAN7v
  KTRiv6F/BD7ixiMeQCXEd1d+OVrgAOeSwhNAvBV7AHHvNAXgFychYEYGVtHzF1mP
  bV1v3WIHctX6Q2h2cmpUe2YP8U+3jOje+Gx63UQ3R4zIuazheI/DmtXlKmTRJNgi
  yKwWtjQud2ejBjTbFj8nK98kx+dDZN4BZ7WLk6p3AoGAJPLXBne/7ieQxRtdhwqe
  1b1KA9TVBf29wadXHCPmNBhyzytUUjhGns4apKmCw4CRh+evGvEvjFmzeiwsqUEN
  AmCmgFxZYtJnSK9UWdbr4T6VK8fsfFhAxFd37P2tuLfe3TZS4vSZQLLtMxfXQNxo
  DVaQNXFpQBvCyQbHbmV86tECgYB/OMyy8IebifjKSm/4KpNA+lWAwK/KhHr/rGjE
  w/SR7ZfbbT6q+686zXk7fPKe7bMtkQRAhk44WzfVlPRS8QVqWLvzCrYTYBQx8Myk
  W5laDJHwbbxIRIOgx2fdGOKQlioIjhEm4+8m6D2MDyTDlSOk9p26wiqyd2tgpjyh
  Bf5HEQKBgFeGY8CFnbXFBsliwNVcBdcQ1irG9AGctwzHsn89pR0somwrnXrqrAe+
  t/jh/nc2ox59gz6yp9vbbohc0IpBDFxfhR7VXxPC7iAKgezGlZ+dViW3RP9Q6a+R
  +zJCWI6yC1tLEc+PyCu7/xzgbGHVdSok8KL8w4YtWW+giop9GVIu
  -----END RSA PRIVATE KEY-----
etcdCaCrt: |
  -----BEGIN CERTIFICATE-----
  MIIC4TCCAcmgAwIBAgIBADANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDEwdldGNk
  LWNhMB4XDTIzMDcyNDA1NTMzOFoXDTMzMDcyMTA1NTMzOFowEjEQMA4GA1UEAxMH
  ZXRjZC1jYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJyULXKoxUw
  SLBUKt91MnXTMEPBehVAVkd9jhnVms1dXcEb6LywUtPcy3i9yUnJ6UsPQYmgN+HN
  wQ4w8y7A6m2uOtHWdNRevt4VY7FOCn1RqijiDFa/oQCx3HeTdBeQKWFy0kQ8aq7X
  EZfPQnEF7H9J+m3M6t8ev3WMFS5uzOi9MWnTP5as3/a3LzDiqVVc8oVzHdi2qSs6
  PC755fYZNIj2PMpbZUZ3y1tOOSYEuSqzJ8mTBD+NRDSvNGuPv4E8/aF/MsIGMDxS
  pRPv7SNhavlcKN1pgi80ERs3LU/pnsoafv2lGhxQA3Oy9SGJGrpvXf1i4PNmXRkK
  vzt5C+AKb4MCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMB
  Af8wHQYDVR0OBBYEFBpNRhNcUOi27qFFg0O/lEnFDIreMA0GCSqGSIb3DQEBCwUA
  A4IBAQB9AtUQuEmd2uZGz72GnmF7VzZF9Wd7+/XpHmC1E9EiAvoUP491v41bU8G8
  KaWO+adSSeDJ+aIA6K8DF8NLH8imzgR9KGKOaDIlHjbfFDg+Gxto1zWtbI5oU5ED
  5PGV/sZbEgDuoI2Bm92clzSDr+liGqHolK3pTm2PIBjymaMFrSFx4NRm7E6uN99P
  FAtaFKsPl+hhUf3sCqhp8+L7B2AGNvlKnyIFzPqPcbzwQgNTTMW725tney9X0Nh8
  6W/YCJmJxzh3v8/MTzEW1QJG1cjPz5vtm4en7xssCIMJO8DGp8XvlGRB9Nv7nP+Y
  1qQec7svIpK/giDwrlD0cgEZEi5Q
  -----END CERTIFICATE-----
etcdCrt: |
  -----BEGIN CERTIFICATE-----
  MIIC7DCCAdSgAwIBAgIIGy7dyB7SxDEwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UE
  AxMHZXRjZC1jYTAgFw0yMzA3MjQwNTUzMzhaGA8yMTIzMDYzMDA2MTcwMlowDjEM
  MAoGA1UEAxMDdGtlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6HAm
  ZxwSw3Nztf8PGZxWrdebQoV+lhiLUxOTIAKXzsj4D/FfMTMPIV1T6ikz391qPvj0
  Z/HG8fO3HiTDvPVQeuHdoHtO8DIvoiNLnwFauoaDsKvLfWxvVx7MBDuMjN3l3xch
  DWCnpgFEhb5zl+waDDsWHcA4G/yqI9prplMg+2N75/aQ7XhQDtgKRziLKA//ckzl
  ANMycYJE6xFFeOCA9Ih+YEOn2p5ahFzcaZdWUksHU07NzCxf8jt1/2/Kj8pe452D
  3JS/QkgA3TtiEci4pAP62/5hwOCfd3l19vrSdIconFOKNWf1XSWmYHF8CnvziwYu
  msf1jHYiQfWW4Qh99wIDAQABo0gwRjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww
  CgYIKwYBBQUHAwIwHwYDVR0jBBgwFoAUGk1GE1xQ6LbuoUWDQ7+UScUMit4wDQYJ
  KoZIhvcNAQELBQADggEBALF4QtOso9Bx/zizy7g0Ub6hwL0gYbjE5VWGMxEfdFXV
  SN2g6qX/DT/fveLcHMoPfLnfqvt1ZpjltsaxSUvbnRXNz8vFxubzYDzsouOIrcIg
  ETz5cLJIbEj75pa5jsaOW/6Z3LyxHSKpFKAkOEpd0bUL4DbVqK/bT7/T2qg2Ir8u
  V1ozK/JZXSyEoHSWorvpchOjbhntTn+axjbwBgc8/XibjshIsJuquBmAunTRIQjg
  w4RwuwTBe4llCcEwh0VxLq7tzlVGln/cMJ1DZyHSXc3hLV3oiowWkXlqEmjBEqX1
  qNdVzTQUEx2OhQ4CucoTliY46OEaFDT8qjRcTctw9uc=
  -----END CERTIFICATE-----
etcdKey: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEA6HAmZxwSw3Nztf8PGZxWrdebQoV+lhiLUxOTIAKXzsj4D/Ff
  MTMPIV1T6ikz391qPvj0Z/HG8fO3HiTDvPVQeuHdoHtO8DIvoiNLnwFauoaDsKvL
  fWxvVx7MBDuMjN3l3xchDWCnpgFEhb5zl+waDDsWHcA4G/yqI9prplMg+2N75/aQ
  7XhQDtgKRziLKA//ckzlANMycYJE6xFFeOCA9Ih+YEOn2p5ahFzcaZdWUksHU07N
  zCxf8jt1/2/Kj8pe452D3JS/QkgA3TtiEci4pAP62/5hwOCfd3l19vrSdIconFOK
  NWf1XSWmYHF8CnvziwYumsf1jHYiQfWW4Qh99wIDAQABAoIBAB5x0hXfT3XaQWWt
  KsUn/RJ4ExX7dkEipd0Ty0l+DXRATn2IF/fRwEGWf89D5k+EKM5mvVyABpbaXTnN
  hvXRC+GMhALpI8XCTQrnpJgHDWMxCz6wwc6DzXGTzxUe16H7zogR93pRFqRftiHu
  eCWF/0Nq2dK7wp2n0oEvsrnuWXuTpFEovo9AV1bPpQDQjnUnJcSxf0SvXgcalSOy
  Cc6Cn2Q9V3ghSqKywG9eIWgLVlzTGUCS9Kz3TIKlaiZLHQN92cDt0Hz91RBSL4Np
  ZfEpBmByWxW28hlcc5qVxh/M9Cm/TcOrXljk87dsqTnoWHXIPTPAA5uW6Hvo8ZCY
  ly1ZmUECgYEA7OBB2he5ZDw/DlUzg+bwH807qXDqWc6C5b/dToz357RP1M8BAjyJ
  jJMkoOcvbZZvH3bumuqTB2KW76HX3L1O2UeqGa12lrwUwyhQ94qxqhRSwvD5RTSJ
  NyzcmVkS2TlplFBgRsxLdFC3ZKS6ufL+B6SLM3LbxMMLdHTMO0FC8IsCgYEA+zQr
  iYEU2m5sQVwGAR6Z8PJj5yhnsRPUTNlktcWaZ+XlSUFP7NW/xnukDJAaLa36Q14K
  JvRUHNt0bTQpXcJpeMMXZgthYKV6GvH3Ql6PyzyktO8D7JVzaYNawMZfn80Gc4Wn
  VWpxx4nqD+l5nDZ8o7qqAEwcvXeKP0qXlxfBicUCgYEAtDWsg8KWzZY0FrBlP807
  E8asxCzebbJ5zVaZhIAkvkdkkK9nwg7SSntLW4pmf8X6BoMR5hPeBblQwUBsnEf9
  q7okw+I/HVA7r3mFl74RiiZqDFsOGUNtvOdJcPTeLRrLowU/Kb2VDgm2bEASuxMN
  hjz9lgelAN2uYkvVcKMmzR8CgYEAzL11qqnpfCq50v+U6T6uy4JTyKjW8q2twEED
  Y1+9/GaU3YL9CJQirTxCtfaRT5/YNSYlciB7mdWH7CWyfXeiDUo8/O/Tmzjj76g9
  FfwKiORRfiK8+QvKODpWMn68m3s4gdlyTBzoxXBztCpf8uE57xyJyJpAZnBS3kkG
  iqBTHt0CgYBH6ffJZ6BoUWqLukFASzHYl9PIewZE9Z3nRcorkgPPthb1RqOyGTla
  vtSO3BZyUWuTLGIfv2/QnOiydqI5e4LjM8ioBzt9joQUFrOBVWwgD/KMEZhVVnIX
  t1FIo8N9JONpKjHuif73V91INU2UFUET8d2Q5u2KJu6lk1RzIwjc0w==
  -----END RSA PRIVATE KEY-----
frontProxyCaCrt: |
  -----BEGIN CERTIFICATE-----
  MIIC7zCCAdegAwIBAgIBADANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDEw5mcm9u
  dC1wcm94eS1jYTAeFw0yMzA3MjQwNTUzMzhaFw0zMzA3MjEwNTUzMzhaMBkxFzAV
  BgNVBAMTDmZyb250LXByb3h5LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
  CgKCAQEAqewf7SY5s3EDHZqsegvHWVYTBBFSGhpTBlHV4fN3bZE90oafWWc0v/2s
  j3W0HMNee++QZv+aKtELd/atBjtRzhzhEBGi1Crtxq5KXCFwiChLUFQGPSAxEtyT
  l8CPD3mAum0sOav3Gj6w6aYtXgrIbrmA+mbAhWBU7Tgyto2wdaYybZnAZCkGZ3B6
  xtKz54+SFzBlm1oa080PQSqrIzepkr39Jtg+d4ME46qGYFg7tevSE3l6SHkEoxws
  88kiwZSMORKaYRmRoYb2g4KOEbCI/A0ah2w2a/sn3CV37Lv1OsuS/+VUjS/QkIl3
  D4+BmIZxo8u/Dn5L8pIOIGkn8kiWRQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQw
  DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU4TqHgHOZAw4WYFkZPDYrrS88vBQw
  DQYJKoZIhvcNAQELBQADggEBADviOCNr4eddneZ4OgcoLR2OFeeOHUWvRvb8iXye
  EXpNxYSLokObxOIt4m7BdOwS5qmwp2qdnTXv4sqRTVm0xxE3gra8oWzp4lRXDRmI
  dMFQ5IqFQxhuTHDeF1NN/jpeWJF+D2c3D1yari2hzss2Lfq0iqu1W+FtxmRXRO78
  QrI6wccXASzc2tdRyEtLUKwjZoyMPenVnkO6XdPGYlzMpMu/g2tTb2wWOakqN8LD
  19drZYaF8uDgkdQzwJ+E2GpmxnUdStawML37ONusp7eTzOxTvO3X5auhcIl0hNEl
  XewsJ4Ux/E/a0t0lDKJEmY1IQJA3FwZdtwhWtB5dZx6PGuo=
  -----END CERTIFICATE-----
passwordCsv: 2T0UJto30HAYr6y0pOdXvA8fbeE,admin,1,administrator
tokenCsv: 2T0UJoVc8KjnROs335rvP23olVT,admin,1,administrator
etcd:
  host: https://172.17.0.2:2379
api:
  replicas: 1
  image: tkestack/tke-auth-api-amd64:v1.9.2.1.g30e412e9.dirty
  redirectHosts: [172.18.0.2, 172.17.0.2]
  oIDCClientSecret: 2T0UJsxRB5Vn0Y8zvJb0Ydp6sGG
controller:
  replicas: 1
  image: tkestack/tke-auth-controller-amd64:v1.9.2.1.g30e412e9.dirty
  adminUsername: admin
  adminPassword: YWRtaW4=
