/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	chart "tkestack.io/tke/api/chart"
	scheme "tkestack.io/tke/api/client/clientset/internalversion/scheme"
)

// ChartGroupListsGetter has a method to return a ChartGroupListInterface.
// A group's client should implement this interface.
type ChartGroupListsGetter interface {
	ChartGroupLists() ChartGroupListInterface
}

// ChartGroupListInterface has methods to work with ChartGroupList resources.
type ChartGroupListInterface interface {
	Create(ctx context.Context, chartGroupList *chart.ChartGroupList, opts v1.CreateOptions) (*chart.ChartGroupList, error)
	Update(ctx context.Context, chartGroupList *chart.ChartGroupList, opts v1.UpdateOptions) (*chart.ChartGroupList, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*chart.ChartGroupList, error)
	List(ctx context.Context, opts v1.ListOptions) (*chart.ChartGroupListList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *chart.ChartGroupList, err error)
	ChartGroupListExpansion
}

// chartGroupLists implements ChartGroupListInterface
type chartGroupLists struct {
	client rest.Interface
}

// newChartGroupLists returns a ChartGroupLists
func newChartGroupLists(c *ChartClient) *chartGroupLists {
	return &chartGroupLists{
		client: c.RESTClient(),
	}
}

// Get takes name of the chartGroupList, and returns the corresponding chartGroupList object, and an error if there is any.
func (c *chartGroupLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *chart.ChartGroupList, err error) {
	result = &chart.ChartGroupList{}
	err = c.client.Get().
		Resource("chartgrouplists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ChartGroupLists that match those selectors.
func (c *chartGroupLists) List(ctx context.Context, opts v1.ListOptions) (result *chart.ChartGroupListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &chart.ChartGroupListList{}
	err = c.client.Get().
		Resource("chartgrouplists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested chartGroupLists.
func (c *chartGroupLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("chartgrouplists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a chartGroupList and creates it.  Returns the server's representation of the chartGroupList, and an error, if there is any.
func (c *chartGroupLists) Create(ctx context.Context, chartGroupList *chart.ChartGroupList, opts v1.CreateOptions) (result *chart.ChartGroupList, err error) {
	result = &chart.ChartGroupList{}
	err = c.client.Post().
		Resource("chartgrouplists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(chartGroupList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a chartGroupList and updates it. Returns the server's representation of the chartGroupList, and an error, if there is any.
func (c *chartGroupLists) Update(ctx context.Context, chartGroupList *chart.ChartGroupList, opts v1.UpdateOptions) (result *chart.ChartGroupList, err error) {
	result = &chart.ChartGroupList{}
	err = c.client.Put().
		Resource("chartgrouplists").
		Name(chartGroupList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(chartGroupList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the chartGroupList and deletes it. Returns an error if one occurs.
func (c *chartGroupLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("chartgrouplists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched chartGroupList.
func (c *chartGroupLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *chart.ChartGroupList, err error) {
	result = &chart.ChartGroupList{}
	err = c.client.Patch(pt).
		Resource("chartgrouplists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
