---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: tke-chart-controller
  name: tke-chart-controller
  namespace: tke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tke-chart-controller
  template:
    metadata:
      labels:
        app: tke-chart-controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tke-chart-controller
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
        - name: tke-chart-controller
          image: tkestack/tke-chart-controller-amd64:d3d6bda7.dirty
          args:
            - -C=/app/conf/tke-chart-controller.toml
          volumeMounts:
            - name: certs-volume
              mountPath: /app/certs
            - name: tke-chart-controller-volume
              mountPath: /app/conf
          ports:
            - containerPort: 9998
          livenessProbe:
            httpGet:
              port: 9998
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: certs-volume
          configMap:
            name: certs
        - name: tke-chart-controller-volume
          configMap:
            name: tke-chart-controller
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-chart-controller
  namespace: tke
data:
  tke-chart-controller.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.platform]
      api_server = "https://tke-platform-api"
      api_server_client_config = "/app/conf/tke-platform-config.yaml"

      [client.chart]
      api_server = "https://tke-chart-api"
      api_server_client_config = "/app/conf/tke-chart-config.yaml"
      [client.registry]
      api_server = "https://tke-registry-api"
      api_server_client_config = "/app/conf/tke-registry-config.yaml"
      [client.auth]
      api_server = "https://tke-auth-api"
      api_server_client_config = "/app/conf/tke-auth-config.yaml"
    [features]
    domain = "RegistryDomain"
    namespace = "RegistryNamespace"


  tke-platform-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-platform-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke

  tke-chart-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-chart-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke
  tke-registry-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-registry-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke
  tke-auth-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-auth-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke
